#### Main parameters

common:
  projectdir: null # Use when loading. If null, here::here() will be used. Can also hard code if for some reason you need that
  project_title: "Test"    # Change depending on your project name
  project_name: "Name" 
  project_description: null # description of project for report, optional
  batch_var: "sample_plate"          # For example, multiple plates
  dose: "dose"               # If there is a dose in the experiment; otherwise use NULL
  platform: "TempO-Seq"      # TempO-Seq Or RNA-Seq
  nmr_threshold: 1000    # 10% of 1M reads for TempOSeq = 100,000; 10% of 10M reads for RNA-Seq = 1,000,000.
  write_additional_output: TRUE # export BMD, biomarker, and biosets output? facet variable should contain chemical and timepoint information
  celltype: "Some cells" # only required for biosets output. Cell type or species used
  units: "uM" # only required for biosets output. Units of dose

###### Alignment and processing pipeline parameters

pipeline:
  genomedir: reference/ # directory where genone information can be found (the files below should be in this directory)
  genome_filename: humansurrogate1_2.fa # filename for genome
  annotation_filename: humansurrogate1_2.gtf # filename for gene annotations
  genome_name: "S1500" # used for labeling genome index files
  sample_id: "sample_ID" # header for the column for 'sample id' in the metadata file. Fasta files should be named sampleid.fa.gz
  mode: se # one of 'se' (single end) or 'pe' (paired end)
  threads: 4 # number of threads to use, for multi-threaded programs

###### QC parameters
QC:
  clust_method: "spearman" # For clustering
  tree_height_cutoff: 0.2  # For clustering
  dendro_color_by: "group" # Specify how you would like to color the dendrograms
  align_threshold: 0.5     # 50% alignment rate for TempO-Seq Experiments
  gini_cutoff: 0.95
  exp_groups:
    one: ["chemical", "dose"]
    two: ["I7_Index_ID", "I5_Index_ID"] 
      #4: ["batch"]
      #As many groups as desired...up to a maximum of 6
  treatment_var: "chemical"
  collapse_replicates: F # Set to true if you have replicate flow cells that need to be summed into a single value
  # Column names for metadata, if applicable
  technical_control: "technical_control"
  reference_rna: "reference_rna"
  solvent_control: "solvent_control"

###### DESeq2 parameters
DESeq2:
  species: "human"                 # one of human, mouse, rat, hamster
  design: "group"                # single experimental group of interest; entries in this column must match the contrast names.
  intgroup: ["group"]            # experimental group of interest plus covariates; can be more than one
  group_facet: "chemical"       # If you have many different experimental groups, you may subset the report by specifying a column in the metadata to filter groups, and then setting the group of interest in group_filter
  group_filter:  null        # Which group will this report be done on?
  display_group_facet: "chemical" #  
  display_group_filter:  null # 
  sortcol: "dose"                # Optionally, a column by which to sort the contrasts
  lenient_contrasts: FALSE         # Use either column (exp, cont) of contrasts file to limit what is included in the report (instead of just exp column)
  strict_contrasts: FALSE         # Use BOTH columns (exp, cont) of contrasts file to limit what is included in the report
  exclude_samples: null      # Optionally, a vector of sample names to exclude from the analysis
  exclude_groups: null       # Optionally, a vector of groups to exclude from the analysis. By default this is assumed to be in the column specified by params$design.
  include_only_column:  null # Restrict analysis to group(s) in the column listed here based on params$include_only_group.
  include_only_group:  null  # Restrict analysis to this/these group(s) within the column listed in params$include_only_column
  cpus: 2                       # Set to a lower number (e.g., 2 to 4) if you aren't working in a server environment
  run_pathway_analysis: TRUE     # Optionally disable pathway analysis if not available for your organism
  wikipathways_directory: "../"
  biospyder_dbs: "./"
  biospyder_manifest_file:  "Human_S1500_1.2_standardized.csv"
  wikipathways_filename: "wikipathways-20210810-gmt-Homo_sapiens.gmt"
  nBestFeatures: 20              # The number of best features to make plots of their counts
  nBest: 100                     # Number of features to include in table and limiting PCA/clustering analysis
  nHeatmap: 50                   # Number of most variable genes for heatmap
  nHeatmapDEGs: 50               # Number of DEGs for heatmap
  cooks: FALSE                   # the DESeq Cook's distance cutoff, or FALSE to disable it
  filter_gene_counts: FALSE      # Filter genes to those with at least 1 count in 1 sample. Disabled by default for biomarker file output. Can enable to increase speed of analysis
  generate_main_report: TRUE
  generate_stats_report: TRUE
  generate_data_explorer_report: TRUE
  generate_go_pathway_report: TRUE
  output_digits: 2
  parallel: TRUE
